// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfVQqPA827suWQuToqkDudnXBlR9UcVlc',
    appId: '1:300528941813:web:3ae5f1cb982354bc01e3bc',
    messagingSenderId: '300528941813',
    projectId: 'mynotes-flutter-project-51323',
    authDomain: 'mynotes-flutter-project-51323.firebaseapp.com',
    storageBucket: 'mynotes-flutter-project-51323.appspot.com',
    measurementId: 'G-FBFH27M05M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-VsRQjl3ohld0s4Z_KR1CYchIJlLL-uU',
    appId: '1:300528941813:android:5e1e4811a21c1b5001e3bc',
    messagingSenderId: '300528941813',
    projectId: 'mynotes-flutter-project-51323',
    storageBucket: 'mynotes-flutter-project-51323.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR1Ng8_VIPPF1TDjsCTk5vCvnUKnAl-ZQ',
    appId: '1:300528941813:ios:59b0a8ec271623ba01e3bc',
    messagingSenderId: '300528941813',
    projectId: 'mynotes-flutter-project-51323',
    storageBucket: 'mynotes-flutter-project-51323.appspot.com',
    iosClientId: '300528941813-586vnm6vhahbh23dnqv7dlai2erffpdt.apps.googleusercontent.com',
    iosBundleId: 'com.urdaddhyy.mynotes',
  );
}
